- mktxp/cli/config/config.py
- mktxp/cli/config/mktxp.conf
- mktxp/collector/connection_collector.py
- mktxp/collector/health_collector.py
- mktxp/datasource/connection_ds.py
- mktxp/datasource/health_ds.py
- mktxp/flow/collector_registry.py
- mktxp/flow/router_entry.py
I RouterOS v7, the response for the `/system/health` endpoint changed slightly.
The API returns a response like this:
`[{'name': 'temperature', 'value': '33', 'type': 'C'}, ...]`
This makes is impossible to just get the value of the desired metric by key, e.g. `voltage`.
Instead, it is necessary to get the records by name and then get its value afterwards.
My fix is working for both v6 and v7.
This PR also adds a new metric. The metric `ip_connections_total` measures the total number of IP connections at time X.
> adapt health datasource to RouterOS v7

- .gitignore
- mktxp/cli/config/config.py
- mktxp/cli/config/mktxp.conf
- mktxp/collector/public_ip_collector.py
- mktxp/datasource/public_ip_ds.py
- mktxp/flow/collector_registry.py
- mktxp/flow/router_entry.py
This PR adds the public IP address as a info metric. The output looks like this:
```txt
mktxp_public_ip_address_info{public_address="109.42.112.253",routerboard_address="10.0.10.1",routerboard_name="RB3011"} 1.0
```
This metric can be activated/deactivated in the config file.
> adds optional public IP address metric

- mktxp/collector/base_collector.py
Hey @akpw,
it's me again. A [user reported](https://github.com/M0r13n/mikrotik_monitoring/issues/10) a crash that occurs if a metric value is None. This seems to have happened before, because some logic already exists that prevents such crashes. [See](https://github.com/akpw/mktxp/blob/9f6c98d651c797ec8385b4aed3d0d7b6a1771c0a/mktxp/collector/base_collector.py#L31).
I generalized this approach and patched relevant places.
> Prevent  crashing if a metric value is None

- mktxp/flow/processor/output.py
Related to https://github.com/akpw/mktxp/issues/42
> use dict.get() to prevent a KeyError when the key "mac_address" does not exists

- mktxp/collector/capsman_collector.py
- mktxp/datasource/capsman_ds.py
This PR adds additional metrics about CAPsMan interfaces.
This is useful when operating multiple CAPs. By adding more metrics about the configuration, channel, frequency and mac address for each cap interface it is easier to debug wireless connectivity issues.
The new metrics roughly look like this (depending on the configuration):
```txt
mktxp_capsman_interfaces_info{configuration="Config-2G",current_channel="2452/20-Ce/gn(20dBm)",current_registered_clients="4",current_state="running-ap",mac_address="FF:FF:FF:FF:FF:FF",name="cap1",routerboard_address="10.0.10.1",routerboard_name="RB3011"} 1.0
mktxp_capsman_interfaces_info{configuration="Family-2G",current_channel="",current_registered_clients="1",current_state="running-ap",mac_address="FF:FF:FF:FF:FF:FF",name="cap2",routerboard_address="1 …
```
> adds capsman interface datasource

- mktxp/flow/router_connection.py
Relates to https://github.com/akpw/mktxp/issues/47
This is a simple patch for the upstream RouterOS-api lib. With this issue in place, string fields are correctly decoded if they contain special characters.
I tested this by adding multiple special characters to a DHCP lease:
> mktxp_dhcp_lease_info{active_address="10.0.10.208",address="10.0.10.208",comment="ROCK äöó²³",host_name="ROCK",mac_address="FF:FF:FF:FF:FF:FF",routerboard_address="10.0.10.1",routerboard_name="RB3011",server="PROD_DHCP"} 377.0
Note the **äöó²³**.
> monkey match the upstream API wrapper

- mktxp/datasource/wireless_ds.py
Mikrotik renamed the field 'signal_strength' to 'signal' when using wifiwave2.
> Rename 'signal' to 'signal_strength' when using wifiwave2

- README.md
As per #55, add a note in the `MKTXP stack install` section regarding usage in Docker Swarm.
- Closes #55
> Add note regarding usage in Docker Swarm

- mktxp/cli/config/_mktxp.conf
- mktxp/cli/config/config.py
- mktxp/flow/collector_handler.py
I am currently monitoring multiple devices. Some of them are a bit old. Thus, their response time is relatively slow. This leads to a rather long scrape duration which in turn requires a longer scrape_interval. While a longer scrape_interval may be fine, it reduces the resolution of the collected metrics, because there are less data points per time.
I added the option to query multiple routers in parallel using a `ThreadPoolExecutor`. This class comes bundled with the `concurrent` module which is part of Pythons standard library. There are two new configuration options to control the behavior of mktxp:
- `fetch_routers_in_parallel`: a boolean value to control if the routers should be queried in parallel or not
- `max_worker_threads`: the max number of concurrent worker threads
If …
> fetch routers in parallel (optionally)

- mktxp/collector/capsman_collector.py
- mktxp/collector/wlan_collector.py
`dhcp_name` is not sufficient to identify wireless clients. DHCP Host Name Option (Code 12) is not required to be unique. As a result, it's possible to have multiple metrics with exactly same labels. Adding `mac_address` label to all wlan/capsman metrics allows to identify the clients.
```
mktxp_wlan_clients_signal_strength{dhcp_name="xyz",routerboard_address="a.b.c.d",routerboard_name="foobar"} -63.0
mktxp_wlan_clients_signal_strength{dhcp_name="xyz",routerboard_address="a.b.c.d",routerboard_name="foobar"} -64.0
mktxp_wlan_clients_signal_strength{dhcp_name="xyz",routerboard_address="a.b.c.d",routerboard_name="foobar"} -65.0
```
vs.
```
mktxp_wlan_clients_signal_strength{dhcp_name="xyz",mac_address="11:22:33:44:55:AA",routerboard_address="a.b.c.d",routerboard_name="foobar"} -63.0 …
```
> Add `mac_address` label to all wlan/capsman metrics

- main.py
- mktxp/cli/config/config.py
- mktxp/cli/config/mktxp.conf
- mktxp/collector/resource_collector.py
- mktxp/utils/utils.py
This PR adds a new metric `system_update_available` to the resource collector. This metric is a boolean gauge that is:
- `0` if the version of ROS is the newest for the current update channel
- `1` if there is a newer version of ROS for the current update channel
Additionally, the label `newest_version` can be used analogously to `version` to display the newest version as a string .This metric allows to show pending updates in Grafana:
I decided to check for updates using the [Mikrotik Changelog RSS feed](https://mikrotik.com/download/changelogs). I explicitly decided against using the  `/system/package/update/check-for-updates` command for this purpose. This is due to security concerns: The `check-for-updates` requires the **write** and **policy** permissions. These permissions …
> Adds new metric: system_update_available

- mktxp/cli/config/config.py
- mktxp/collector/kid_control_device_collector.py
- mktxp/datasource/kid_control_device_ds.py
- mktxp/flow/collector_registry.py
- mktxp/flow/router_entry.py
This PR adds metrics for kid-control devices.
It creates an info metric like this:
```
mktxp_kid_control_device_info{disabled="0",ip_address="192.168.88.21",mac_address="DE:AD:BE:EF",name="my device,routerboard_address="192.168.88.1",routerboard_name="test",user="kid1"} 1.0
```
And various metrics:
```
mktxp_kid_control_device_bytes_down{name="my device",mac_address="DE:AD:BE:EF",routerboard_address="192.168.88.1",routerboard_name="test"} 5.007774e+06
mktxp_kid_control_device_bytes_up{name="my device",mac_address="DE:AD:BE:EF",routerboard_address="192.168.88.1",routerboard_name="test"} 3.173021e+06
mktxp_kid_control_device_rate_down{name="my device",mac_address="DE:AD:BE:EF",routerboard_address="192.168.88.1",routerboard_name="test"} 0.0
mktxp_kid_control_device_rate_up{name="my …
```
> Added metrics for kid-control devices

- mktxp/cli/output/wifi_out.py
- mktxp/datasource/capsman_ds.py
- mktxp/datasource/wireless_ds.py
- mktxp/flow/processor/output.py
As of RouterOS version 7.13, `/interface/wifiwave2` has been renamed to `/interface/wifi`.
> !) wifi - split existing "wifiwave2" package into separate packages
> "wifi-qcom", "wifi-qcom-ac", and include required utilities for WiFi
> management into bundle;
Please see links below for more information:
[1] https://mikrotik.com/download/changelogs/testing-release-tree
[2] https://help.mikrotik.com/docs/display/ROS/WiFi
> Add support for RouterOS version 7.13

- mktxp/datasource/system_resource_ds.py
- mktxp/flow/router_entry.py
- mktxp/utils/utils.py
As stated in the issue: https://github.com/akpw/mktxp/issues/106
New versions of RouterOS (>7.13) have the wifi capsman ability builtin.
Added functionality to check if the routeros version is post 7.13, and use wifi wireless version if so.
> Add Parsing of the routeros version for capsman metrics

- mktxp/flow/router_connection.py
Routers running RouterOS versions below 6.43 do not support plain text authentication.
The connection process was improved to attempt both authentication methods.
> Retry connection without plain text authentication

- mktxp/collector/dhcp_collector.py
- mktxp/datasource/dhcp_ds.py
This adds some currently missing metrics to the export. Especially `client-id` is important, because this is the [RFC4361)](https://www.rfc-editor.org/rfc/rfc4361) client id which is used by many clients (Ubuntu 22.04 with netplan uses this ID rather than the MAC by default).
> feat: adds additional metrics for DHCP

- mktxp/collector/firewall_collector.py
- mktxp/datasource/firewall_ds.py
I noticed that the exporter tool currently doesn't support collecting metrics for NAT and mangle firewall rules. I've implemented support for this feature.
Related to akpw/mktxp#118
> NAT and mangle firewall metrics collection

- mktxp/collector/user_collector.py
user collector wrongly uses installed_packages parameter to determine if logged user data is to be collected, instead of the user parameter.
> Fix wrong config item being used in user collector

- .github/workflows/build-and-push.yaml
closes https://github.com/akpw/mktxp/issues/185
- add semver tags to the images, matching the semver tags in git
- migrate off the workflow template, which had deprecated commands and NodeJS versions
> ci: new image build workflow

- mktxp/collector/public_ip_collector.py
Mikrotik has thankfully added the public IPv6 prefix to the `/ip/cloud` output, though I’m not sure when this feature was introduced. There doesn’t seem to be a changelog that mentions it, but it is present in RouterOS 7.15.3 and later.
> feat: includes public_address_ipv6

- .dockerignore
- Dockerfile
- README.md
- mktxp/cli/config/config.py
- mktxp/cli/config/mktxp.conf
- mktxp/collector/routing_stats_collector.py
- mktxp/datasource/routing_stats_ds.py
- mktxp/flow/collector_registry.py
- mktxp/flow/router_entry.py
Adding a new `routing_stats` collector to export the data from `/routing/stats/process/print` to collect CPU and memory utilization from different routing related processes.
This PR also includes a small change to the Dockerfile to allow more stages of the docker build to be cached.
> Add Routing Process Stats collector

- .github/workflows/build-and-push.yaml
At the moment the tags for the docker image are only provided for releases, tags and branches. There are no tags extracted for PRs, this results in an empty tag list and the pipeline fails for PRs. This change enables the push only for the main branch and releases.
If you would like to push an image for every PR the following line has to be added.
```
tags: |
....
type=ref,event=pr
```
> Only push image on main branch and releases

- mktxp/collector/monitor_collector.py
* Add interface_sfp_info as Info metric with vendor information as label
* Add additional metrics
* supply voltage
* rx loss state
* tx bias current
* tx fault state
> Add additional SFP information

- mktxp/collector/base_collector.py
The text for HELP is called 'documentation' in the python prometheus-client package. Instead of fixing the typo in 'decription' it has been renamed to 'documentation'. Currently the parameter name 'decription' is not used in any function call. So this change should not break anything.
> Fix typo and rename decription to documentation

- mktxp/cli/config/config.py
- mktxp/cli/config/mktxp.conf
- mktxp/collector/bfd_collector.py
- mktxp/datasource/bfd_ds.py
- mktxp/flow/collector_registry.py
- mktxp/flow/router_entry.py
Add support to collect metrics for the Bidirectional Forwarding Detection (BFD). Tested with RouterOS 7.x
> Add support to collect bfd metrics

- mktxp/collector/certificate_collector.py
It has been added in `v1.2.10` in metric `mktxp_certificate_expiration_timestamp_seconds`
> Fix scrape on metric `mktxp_certificate_expiration_timestamp_seconds` due to usage of `-`

- README.md
- mktxp/cli/config/config.py
- mktxp/cli/config/mktxp.conf
- mktxp/flow/router_connection.py
This PR allows to specify the path to a custom CA file instead of using the default system store. This way the custom CA does not have to be added to the system store in case you don't want every application to trust it.
> Allow to use a custom CA

- deploy/kubernetes/secret.yaml
- mktxp/cli/config/config.py
- mktxp/flow/router_connection.py
- setup.py
There's currently no way to use this with nixos without having a plaintext password living in your nix store. This PR adds support for a credentials file in place of plaintext credentials, which allows this exporter to work well with [nix-sops](https://github.com/Mic92/sops-nix) and similar secret management packages.
> Add support for a credentials file

- mktxp/cli/config/config.py
- mktxp/cli/config/mktxp.conf
- mktxp/flow/router_connection.py
- no_ssl_certificate = true
- The changes in #236 broke the expected behaviour
- This allows to connect without certificate using an anonymous Diffie-Hellman cipher
- ssl_check_hostname
- Enable/disable the check of the peer hostname in the certificate
Please check if everything is working as expected.
If a ca file is provided with ```create_default_context()``` it should already call ```load_verify_locations()```
See: https://github.com/python/cpython/blob/5a7f5ea631aa658f92d651a32d1d064fe9818156/Lib/ssl.py#L716-L717
In #236 the possibility to connect without an certificate has been removed by removing the following line.
```
ctx.set_ciphers('ADH:@SECLEVEL=0') 
```
This PR restores the expected behaviour for connections without certificate. The other changes are mostly adapted from …
> Fix some unclear ssl handling

- mktxp/utils/utils.py
Hi,
I face this problem `update feed returned: HTTP Error 404: Not Found` - `Fetching available ROS releases from https://mikrotik.com/candidate.rss`. When I look deeper, I see that they change the RSS address. So I created this pull request.
> change channel rss mapping for testing channel
